services:
  bola-api:
    build: .
    container_name: bola-api-js
    ports:
      - "3000:3000"
    restart: unless-stopped
  zap:
      image: zaproxy/zap-stable
      container_name: zap-scanner
      depends_on:
        - bola-api
      command: tail -f /dev/null   # Prevents auto-start
      volumes:
        - ./zap-reports:/zap/wrk